In [1]:
# read cs
import pandas as pd

In [3]:
df = pd.read_csv('student.csv') #A CSV file means Comma-Separated Values    #It is simply a text file that stores data in rows and columns.
df
#read_csv tells the pandas what kind of reader should they use
#student.csv is written as file extension

   S.N     Name  Age City
0    1   Rakesh   35  Ktm
1    2  Prakash   30  Bkt
2    3   Barsha   28  Ltp
3    4    Sneha   20  Ktm
4    5  Abhiyan   32  Brt
5    6   Anisha   40  Ltp
6    7   Parash   50  Rjb
7    8    Kiran   60  Brt
8    9      Ram   42  NaN

In [4]:
df.info()# gives structure of data
# non null count tells is there  mising data

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   S.N     9 non-null      int64
 1   Name    9 non-null      str
 2   Age     9 non-null      int64
 3   City    8 non-null      str
dtypes: int64(2), str(2)
memory usage: 420.0 bytes

In [6]:
df.describe() #stastical information

            S.N        Age
count  9.000000   9.000000
mean   5.000000  37.444444
std    2.738613  12.135806
min    1.000000  20.000000
25%    3.000000  30.000000
50%    5.000000  35.000000
75%    7.000000  42.000000
max    9.000000  60.000000

In [7]:
# finding mising or null value
df.isnull().sum()

S.N     0
Name    0
Age     0
City    1
dtype: int64

In [8]:
df.count() #counts the no of data in column

S.N     9
Name    9
Age     9
City    8
dtype: int64

In [9]:
#dispaly unique data (one column at the timme mean dispaly the data once )
df['Name'].unique()

<StringArray>
[ 'Rakesh', 'Prakash',  'Barsha',   'Sneha', 'Abhiyan',  'Anisha',  'Parash',
   'Kiran',     'Ram']
Length: 9, dtype: str

In [10]:
#find column
df.columns

Index(['S.N', 'Name', 'Age', 'City'], dtype='str')

In [12]:
df['City'].value_counts()
# FIND the data how many times they are repeated

City
Ktm    2
Ltp    2
Brt    2
Bkt    1
Rjb    1
Name: count, dtype: int64