In [1]:
# Z Score = (Xi- meu)/Sigma
#  where xi = individual age, salary value
#  meu = mean of age , salary
# sigma = standard deviation
# (z - scorescaling)
# two type
# standardlization z-score
# normalization min,max 
#after scaling brings mean to zero(0) and std dev to one(1)

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Social_Network_Ads.csv")
df.head()# display first five row

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [13]:
# df = df.iloc [:,2:0]#iloc means select rows and 
# columns by their numerical position.
# # df.iloc[rows, columns(first no say start from that coulmn no and second number say just stop before this column]


# df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[400 rows x 0 columns]

In [26]:
X = df.drop('Purchased', axis=1)
X#Remove the Purchased column from df and put everything else into X.

y = df['Purchased']
y #Take the Purchased column from df and put it into y.

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [33]:
X = df.drop("Gender", axis=1)
X

      User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y, test_size=0.2,random_state=1)

In [36]:
X_train

      User ID  Age  EstimatedSalary  Purchased
93   15699284   29            28000          0
23   15599081   45            22000          1
299  15747043   46           117000          1
13   15704987   32            18000          0
90   15684801   22            81000          0
..        ...  ...              ...        ...
255  15750056   52            90000          1
72   15595228   20            23000          0
396  15706071   51            23000          1
235  15646227   46            79000          1
37   15689425   30            49000          0

[320 rows x 4 columns]

In [37]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)#learns how to scale it

StandardScaler()

In [38]:
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[ 0.06699777, -0.80330081, -1.19121795, -0.72876641],
       [-1.32816737,  0.75697997, -1.36859801,  1.3721818 ],
       [ 0.73196481,  0.85449752,  1.43991958,  1.3721818 ],
       ...,
       [ 0.1614958 ,  1.34208527, -1.33903467,  1.3721818 ],
       [-0.67173537,  0.85449752,  0.31651254,  1.3721818 ],
       [-0.0702729 , -0.70578326, -0.57038775, -0.72876641]],
      shape=(320, 4))

In [18]:
#normalization is feature scaling technique which  brings value in range of 0 and 1

In [41]:
# normalization :
from sklearn.preprocessing import MinMaxScaler#MinMaxScaler checks the value's position between MIN and MAX and converts that position to 0–1. ✅
mms = MinMaxScaler()
mmscaled = mms.fit(X_train)
mms_x_train_scaled = mms.transform(X_train)
mms_x_train_scaled

array([[0.53348059, 0.26190476, 0.0962963 , 0.        ],
       [0.13032545, 0.64285714, 0.05185185, 1.        ],
       [0.72563338, 0.66666667, 0.75555556, 1.        ],
       ...,
       [0.5607873 , 0.78571429, 0.05925926, 1.        ],
       [0.32001191, 0.66666667, 0.47407407, 1.        ],
       [0.49381405, 0.28571429, 0.25185185, 0.        ]], shape=(320, 4))

In [42]:

mms = MinMaxScaler()
mmscaled = mms.fit(X_test)
mms_x_test_scaled = mms.transform(X_test)
mms_x_test_scaled

array([[0.77181887, 0.42857143, 0.13953488, 0.        ],
       [0.53034366, 0.5       , 0.35658915, 0.        ],
       [0.9439092 , 0.42857143, 0.79844961, 1.        ],
       [0.40019235, 0.5       , 0.82945736, 1.        ],
       [0.93687287, 0.19047619, 0.79844961, 0.        ],
       [0.61586214, 0.47619048, 0.3875969 , 0.        ],
       [0.46049246, 0.04761905, 0.1627907 , 0.        ],
       [0.11191929, 0.73809524, 0.57364341, 1.        ],
       [0.41641339, 0.30952381, 0.02325581, 0.        ],
       [0.28730296, 0.71428571, 0.97674419, 0.        ],
       [0.31082679, 0.38095238, 0.44186047, 0.        ],
       [0.25082646, 0.5       , 0.4496124 , 0.        ],
       [0.43535735, 0.4047619 , 0.44186047, 0.        ],
       [0.02334063, 0.71428571, 0.89922481, 1.        ],
       [0.17299381, 0.83333333, 0.51937984, 1.        ],
       [0.48173885, 0.9047619 , 0.91472868, 1.        ],
       [0.85394826, 1.        , 0.52713178, 1.        ],
       [0.66254757, 0.21428571, 0.33333333, 0.        ],
       [0.40645844, 0.23809524, 0.55813953, 0.        ],
       [0.10023232, 1.        , 0.6744186 , 1.        ],
       [0.6444363 , 0.52380952, 0.46511628, 0.        ],
       [0.87821319, 0.76190476, 0.56589147, 1.        ],
       [0.60779326, 0.61904762, 0.96124031, 1.        ],
       [0.21998734, 0.69047619, 0.21705426, 0.        ],
       [0.19918645, 0.64285714, 0.08527132, 1.        ],
       [1.        , 0.19047619, 0.        , 0.        ],
       [0.01969756, 0.95238095, 0.24806202, 1.        ],
       [0.57687504, 0.73809524, 0.45736434, 0.        ],
       [0.87096036, 0.83333333, 0.14728682, 1.        ],
       [0.93647734, 0.80952381, 0.76744186, 0.        ],
       [0.41112157, 0.5       , 0.20930233, 0.        ],
       [0.97576421, 0.02380952, 0.47286822, 0.        ],
       [0.03787544, 0.        , 0.5503876 , 0.        ],
       [0.65711002, 0.92857143, 0.45736434, 1.        ],
       [0.11825616, 0.21428571, 0.53488372, 0.        ],
       [0.10940037, 0.28571429, 0.50387597, 0.        ],
       [0.30495208, 0.0952381 , 0.02325581, 0.        ],
       [0.06205294, 0.33333333, 0.5503876 , 0.        ],
       [0.35246188, 0.76190476, 0.03875969, 1.        ],
       [0.71384617, 0.02380952, 0.07751938, 0.        ],
       [0.73511754, 0.69047619, 1.        , 1.        ],
       [0.37981614, 0.95238095, 0.66666667, 1.        ],
       [0.00537509, 0.38095238, 0.7751938 , 0.        ],
       [0.10614451, 0.11904762, 0.39534884, 0.        ],
       [0.85640889, 0.9047619 , 0.34883721, 1.        ],
       [0.3926106 , 0.30952381, 0.79844961, 1.        ],
       [0.4116878 , 0.71428571, 0.15503876, 1.        ],
       [0.68419782, 0.69047619, 0.75968992, 1.        ],
       [0.73883971, 0.5       , 0.49612403, 0.        ],
       [0.18058389, 0.80952381, 0.17829457, 1.        ],
       [0.61798969, 0.14285714, 0.33333333, 0.        ],
       [0.21870915, 0.45238095, 0.29457364, 0.        ],
       [0.63021375, 0.57142857, 0.50387597, 1.        ],
       [0.56183228, 0.66666667, 0.10077519, 1.        ],
       [0.43258029, 0.57142857, 0.4496124 , 1.        ],
       [0.25576022, 0.45238095, 0.36434109, 0.        ],
       [0.92318325, 1.        , 0.20930233, 1.        ],
       [0.0907312 , 0.42857143, 0.28682171, 0.        ],
       [0.        , 0.95238095, 0.62015504, 1.        ],
       [0.03277931, 0.5952381 , 0.88372093, 1.        ],
       [0.91689635, 0.21428571, 0.57364341, 0.        ],
       [0.35361934, 0.11904762, 0.51937984, 0.        ],
       [0.20720121, 0.47619048, 0.75193798, 0.        ],
       [0.28462583, 0.4047619 , 0.27131783, 0.        ],
       [0.54116462, 0.42857143, 0.65116279, 1.        ],
       [0.52142958, 0.45238095, 1.        , 1.        ],
       [0.56850222, 0.19047619, 0.15503876, 0.        ],
       [0.61724859, 0.57142857, 0.42635659, 0.        ],
       [0.46261169, 0.5952381 , 0.91472868, 0.        ],
       [0.68416035, 0.47619048, 0.27131783, 0.        ],
       [0.40400197, 0.66666667, 0.62790698, 0.        ],
       [0.58205861, 0.4047619 , 0.2248062 , 0.        ],
       [0.96124606, 0.47619048, 0.75968992, 1.        ],
       [0.2397307 , 0.5       , 0.43410853, 0.        ],
       [0.15252184, 0.19047619, 0.28682171, 0.        ],
       [0.82649824, 0.85714286, 0.72093023, 1.        ],
       [0.09273801, 0.35714286, 0.27906977, 0.        ],
       [0.48269646, 0.19047619, 0.00775194, 0.        ],
       [0.64958656, 0.28571429, 0.55813953, 0.        ],
       [0.02232057, 0.4047619 , 0.34883721, 0.        ]])